# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0003_auto_20160618_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='private',
            field=models.BooleanField(),
        ),
    ]
